title: Queensland Government Digital Capability Hub
url: "https://qld-gov-au.github.io"
baseurl: "/digitalcapability"

# Keep permalink structure simple for Pages
permalink: pretty

# Exclude build cache and site output
exclude:
  - .jekyll-cache
  - _site
